In [4]:
# Creating homogenous lists = Elements of same data type
# 1. List of integers
l1 = list(range(10))
print(l1)
print([type(item) for item in l1])
# 2. List of floting points
l2 = [float(x) for x in l1]
print(l2)
print([type(item) for item in l2])
# 3. List of strings
l3 = [str(c) for c in l1]
print(l3)
print([type(item) for item in l3])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[<class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>, <class 'int'>]
[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]
[<class 'float'>, <class 'float'>, <class 'float'>, <class 'float'>, <class 'float'>, <class 'float'>, <class 'float'>, <class 'float'>, <class 'float'>, <class 'float'>]
['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
[<class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>, <class 'str'>]


In [5]:
# Creating heterogenous list = Elements of different data types
l = [10, 3.14, 'hello', True, (2+3j)]
print(l)
print([type(item) for item in l])

[10, 3.14, 'hello', True, (2+3j)]
[<class 'int'>, <class 'float'>, <class 'str'>, <class 'bool'>, <class 'complex'>]


In [ ]:
# Arrays in Python (Using the built-in array module)
import array
# Creating a list
l = list(range(10))
print(l)
print(type(l))
# array() = Function to create an array
# 1. Array of integers (Using the type code 'i')
a1 = array.array('i', l)
print(a1)
print(type(a1))
# 2. Array of floating points (Using the type code 'f')
a2 = array.array('f', l)
print(a2)
print(type(a2))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>
array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
<class 'array.array'>
array('f', [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0])
<class 'array.array'>


In [12]:
import numpy as np
# array() = Function to create array
# Creating NumPy arrays from lists
a1 = np.array([1, 2, 3, 4, 5])
print(a1)
print(type(a1))
# Creating NumPy arrays using range()
a2 = np.array(range(10))
print(a2)
print(type(a2))

[1 2 3 4 5]
<class 'numpy.ndarray'>
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [16]:
# Type promotion in NumPy arrays
import numpy as np
# Creating a list of elements with integer and float data types 
l = [1, 2, 3.14, 4, 5]
print(l)
print([type(item) for item in l])
# Creating a NumPy array from this list
a = np.array(l)
print(a)
print([type(item) for item in a])

[1, 2, 3.14, 4, 5]
[<class 'int'>, <class 'int'>, <class 'float'>, <class 'int'>, <class 'int'>]
[1.   2.   3.14 4.   5.  ]
[<class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>]


In [21]:
# Explicitly set data type of NumPy arrays using dtype keyword
import numpy as np
# From int to float
arr1 = np.array([1, 2, 3, 4, 5], dtype=float)
print(arr1)
print([type(item) for item in arr1])
# From float to int
arr2 = np.array([1.2, 3.4, 5.6, 7.8, 9.0], dtype=int)
print(arr2)
print([type(item) for item in arr2])
# From int to bool
arr3 = np.array([0, 1, 2, 3, 4], dtype=bool)
print(arr3)
print([type(item) for item in arr3])
# From float to complex
arr4 = np.array([1.2, 3.4, 5.6, 7.8, 9.0], dtype=complex)
print(arr4)
print([type(item) for item in arr4])

[1. 2. 3. 4. 5.]
[<class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>, <class 'numpy.float64'>]
[1 3 5 7 9]
[<class 'numpy.int64'>, <class 'numpy.int64'>, <class 'numpy.int64'>, <class 'numpy.int64'>, <class 'numpy.int64'>]
[False  True  True  True  True]
[<class 'numpy.bool'>, <class 'numpy.bool'>, <class 'numpy.bool'>, <class 'numpy.bool'>, <class 'numpy.bool'>]
[1.2+0.j 3.4+0.j 5.6+0.j 7.8+0.j 9. +0.j]
[<class 'numpy.complex128'>, <class 'numpy.complex128'>, <class 'numpy.complex128'>, <class 'numpy.complex128'>, <class 'numpy.complex128'>]


In [33]:
# Creating multidimensional arrays
import numpy as np
# 1. From nested lists
# Each list represents a single row
m1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m1)
# 2. Using range()
# Outer range() is for rows and inner range() is for columns in each row
m2 = np.array([range(i, i+3) for i in range(5)])
print(m2)
# 3. Combination of both
m3 = np.array([range(i, i+5) for i in [2, 4, 6, 8]])
print(m3)
m4 = np.array([[1, 2, 3] for i in range(5)])
print(m4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]]
[[ 2  3  4  5  6]
 [ 4  5  6  7  8]
 [ 6  7  8  9 10]
 [ 8  9 10 11 12]]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [51]:
# Creating NumPy arrays from scratch
import numpy as np
# 1. zeros() = Create an array filled with 0s
# 1D array
a1 = np.zeros(10, dtype=int)
print(a1)
# 2D array
m1 = np.zeros((2,3), dtype=float)
print(m1)
print()

# 2. ones() = Create an array filled with 1s
# 1D array
a2 = np.ones(10, dtype=int)
print(a2)
# 2D array
m2 = np.ones((3,4), dtype=float)
print(m2)
print()

# 3. full() = Creates an array filled with a specific value
# 1D array
a3 = np.full(10, 5)
print(a3)
# 2D array
m3 = np.full((3,3), 3.14)
print(m3)
print()

# 4. arange(start, stop, step) = Creates an array filled with a linear sequence from start (inclusive) to stop (exclusive) of difference step
a4 = np.arange(0, 20, 2)
print(a4)
print()

# 5. linspace(start, stop, space) = Creates an array of evenly spaced numbers over a specified interval
a5 = np.linspace(0, 1, 5)
print(a5)
print()

# 6. empty() = Creates an uninitialized array of integers
a6 = np.empty(8)
print(a6)
print()

# 7. eye() = Create an identity matrix
i = np.eye(3)
print(i)
print()

[0 0 0 0 0 0 0 0 0 0]
[[0. 0. 0.]
 [0. 0. 0.]]

[1 1 1 1 1 1 1 1 1 1]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[5 5 5 5 5 5 5 5 5 5]
[[3.14 3.14 3.14]
 [3.14 3.14 3.14]
 [3.14 3.14 3.14]]

[ 0  2  4  6  8 10 12 14 16 18]

[0.   0.25 0.5  0.75 1.  ]

[1. 1. 1. 1. 1. 1. 1. 1.]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



In [60]:
# random module provides functions for generating random numbers
import numpy as np
# 1. random() = Generates random floats in [0.0, 1.0)
# 1D array
a1 = np.random.random(5)
print(a1)
# 2D array
m1 = np.random.random((3,3))
print(m1)
print()

# 2. normal() = Generates random values with mean 3 and standard deviation 2.5
# 1D array
a2 = np.random.normal(3, 2.5, 5)
print(a2)
m2 = np.random.normal(0, 1, (3,3))
print(m2)
print()

# 3. randint() = Generate random integers in the given interval
# 1D array
a3 = np.random.randint(0, 10, 5)
print(a3)
# 2D array
m3 = np.random.randint(10, 20, (3,3))
print(m3)
print()

[0.26704093 0.55768966 0.61517222 0.83165631 0.52414272]
[[0.52488253 0.48833095 0.82265512]
 [0.73757628 0.47165557 0.45592403]
 [0.44750018 0.58239504 0.11634504]]

[-0.83858805 -1.31805856 -1.39320954  1.32050707  1.07528512]
[[ 0.27404532 -0.29049403 -0.85095304]
 [ 0.06320099  0.31653914 -0.02089272]
 [ 0.75615238  0.31113869 -0.36418466]]

[6 9 7 9 9]
[[17 12 17]
 [12 18 17]
 [17 18 15]]

