# Attributes

In [2]:
# Creating different arrays
import numpy as np
# 1D array
a1 = np.random.randint(0, 10, 5)
print(a1)
# 2D array
a2 = np.random.randint(0, 10, (2,3))
print(a2)
# 3D array
a3 = np.random.randint(0, 10, (3,2,4))
print(a3)

[5 8 3 7 4]
[[7 5 5]
 [7 3 1]]
[[[5 2 6 3]
  [2 8 7 8]]

 [[1 9 4 4]
  [8 2 4 7]]

 [[5 7 1 9]
  [2 2 0 8]]]


In [ ]:
# Attributes of 1D array
print("Data type =", a1.dtype)
print("Dimension =", a1.ndim)
print("Shape =", a1.shape)
print("Size =", a1.size)

Data type = int32
Dimension = 1
Shape = (5,)
Size = 5


In [4]:
# Attributes of 2D array
print("Data type =", a2.dtype)
print("Dimension =", a2.ndim)
print("Shape =", a2.shape)
print("Size =", a2.size)

Data type = int32
Dimension = 2
Shape = (2, 3)
Size = 6


In [5]:
# Attributes of 3D array
print("Data type =", a3.dtype)
print("Dimension =", a3.ndim)
print("Shape =", a3.shape)
print("Size =", a3.size)

Data type = int32
Dimension = 3
Shape = (3, 2, 4)
Size = 24


# Indexing

In [ ]:
# 1D array
import numpy as np
# Create a 1D array of integers
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(arr)
# Positive indexing is as follows:
#  0  1  2  3  4  5  6  7
# 10 20 30 40 50 60 70 80 
# Accessing elements:
print(arr[3])
print(arr[6])
# Negative indexing is as follows:
# -8 -7 -6 -5 -4 -3 -2 -1
# 10 20 30 40 50 60 70 80
# Accessing elements:
print(arr[-6])
print(arr[-3])
# Modifying values
arr[2] = 90
arr[-2] = 90
print(arr)

[10 20 30 40 50 60 70 80]
40
70
30
60
[10 20 90 40 50 60 90 80]


In [5]:
# 2D array
import numpy as np
# Create a 2D array of integers
mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(mat)
# Positive indexing is as follows:
#   0 1 2
# 0 1 2 3
# 1 4 5 6
# 2 7 8 9
# Accessing elements:
print(mat[0,2])
print(mat[2,1])
# Negative indexing is as follows:
#    -3 -2 -1
# -3  1  2  3
# -2  4  5  6
# -1  7  8  9
# Accessing elements:
print(mat[-3,-2])
print(mat[-2,-1])
# Modifying values:
mat[2,0] = 0
mat[-3,-1] = 0
print(mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
8
2
6
[[1 2 0]
 [4 5 6]
 [0 8 9]]


# Slicing

In [ ]:
# 1D array
import numpy as np
x = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
print(x)
# Syntax = x[start:stop:step]
# Default values are start = 0, stop = size of array and step = 1
# Indexing is as follows:
#  0  1  2  3  4  5  6  7  8
# 10 20 30 40 50 60 70 80 90

# 1. Upto index 3 (First 3 elements)
# Index 0, 1, 2
print(x[:3])

# 2. From index 3
# Index 3, 4, 5, 6, 7, 8
print(x[3:])

# 3. Middle subarray
print(x[2:6])

# 4. Every second element from beginning to end of array
# Index 0, 2, 4, 6, 8
print(x[::2])

# 5. Every second element, starting from index 3
# Index 3, 5, 7
print(x[3::2])

# 6. Entire array reversed
# step = -1 (start and stop are swapped)
# Index 8, 7, 6, 5, 4, 3, 2, 1, 0
print(x[::-1])

# 7. Every second element from index 4 reversed
# Index 4, 2, 0
print(x[4::-2])

[10 20 30 40 50 60 70 80 90]
[10 20 30]
[40 50 60 70 80 90]
[30 40 50 60]
[10 30 50 70 90]
[40 60 80]
[90 80 70 60 50 40 30 20 10]
[50 30 10]


In [23]:
# 2D array
import numpy as np
x = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(x)
# Syntax = x[start:stop:step, start:stop:step]
# Indexing is as follows:
#    0  1  2
# 0 10 20 30
# 1 40 50 60
# 2 70 80 90

# 1. Single row
print(x[2, :])

# 2. Row slice (Multiple rows)
print(x[0:2])

# 3. Single column
print(x[:, 1])

# 4. Column slice (Multiple columns)
print(x[:, 1:3])

# 5. First 2 rows and 2 columns
print(x[0:2, 0:2])

# 6. 3 rows, every second column
print(x[0:3, ::2])

# 7. All rows and columns reversed
print(x[::-1, ::-1])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[70 80 90]
[[10 20 30]
 [40 50 60]]
[20 50 80]
[[20 30]
 [50 60]
 [80 90]]
[[10 20]
 [40 50]]
[[10 30]
 [40 60]
 [70 90]]
[[90 80 70]
 [60 50 40]
 [30 20 10]]


In [28]:
# List slicing vs Array slicing
import numpy as np

# List
l = [10, 20, 30, 40, 50, 60]
print(l)
# List slicing creates a copy
l_sub = l[2:5]
print(l_sub)
# Modifying l_sub
l_sub[1] = 99
print(l)

# Array
a = np.array([10, 20, 30, 40, 50, 60])
print(a)
# Array slicing creates a view
a_sub = a[2:5]
print(a_sub)
# Modifying a_sub
a_sub[1] = 99
print(a)

[10, 20, 30, 40, 50, 60]
[30, 40, 50]
[10, 20, 30, 40, 50, 60]
[10 20 30 40 50 60]
[30 40 50]
[10 20 30 99 50 60]


In [31]:
# Creating copies of NumPy arrays
import numpy as np
a = np.array([10, 20, 30, 40, 50, 60])
print(a)
# copy() = Method to explicitly declare a subarray as a copy of the array
a_sub_copy = a[2:5].copy()
print(a_sub_copy)
# Modifying a_sub_copy
a_sub_copy[1] = 99
print(a)

[10 20 30 40 50 60]
[30 40 50]
[10 20 30 40 50 60]


# Reshaping

In [37]:
# reshape() = Method to reshape array (Size of initial array must be equal to size of final array)
import numpy as np
# Create a 1D array
arr_1 = np.arange(12)
print(arr_1)
# Reshape to 2D array
arr_2 = arr_1.reshape(3, 4)
print(arr_2)
# Reshape to 3D array
arr_3 = arr_1.reshape(2, 3, 2)
print(arr_3)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [42]:
# Converting 1D array into 2D row or column matrix
import numpy as np
arr = np.array([10, 20, 30])
print(arr, arr.ndim, arr.shape)
# Matrix with 1 row and 3 columns (Row vector)
x = arr.reshape(1, 3)
print(x, x.ndim, x.shape)
# Matrix with 1 column and 3 rows (Column vector)
y = arr.reshape(3, 1)
print(y, y.ndim, y.shape)

[10 20 30] 1 (3,)
[[10 20 30]] 2 (1, 3)
[[10]
 [20]
 [30]] 2 (3, 1)


In [44]:
# Using newaxis instead of the above method
import numpy as np
arr = np.array([10, 20, 30])
print(arr, arr.ndim, arr.shape)
# Row vector
x = arr[np.newaxis, :]
print(x, x.ndim, x.shape)
# Column vector
y = arr[:, np.newaxis]
print(y, y.ndim, y.shape)

[10 20 30] 1 (3,)
[[10 20 30]] 2 (1, 3)
[[10]
 [20]
 [30]] 2 (3, 1)


# Joining

In [45]:
# 1D arrays
import numpy as np
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = np.array([7, 8, 9])
res = np.concatenate([x, y, z])
print(res)

[1 2 3 4 5 6 7 8 9]


In [ ]:
# 2D arrays (Same dimensions)
import numpy as np
# Two 2D arrays of dimension 2 X 2
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
# Concatenate along first axis
m1 = np.concatenate([a, b])
print(m1)
# Concatenate along second axis
m2 = np.concatenate([a, b], axis=1)
print(m2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [57]:
# 2D arrays (Different dimensions)
import numpy as np
# Dimension 1 X 3
x = np.array([[1, 2, 3]])
# Dimension 2 X 3
y = np.array([[4, 5, 6], [7, 8, 9]])
# Dimension 2 X 1
z = np.array([[0], [0]])
# Vertically stack x and y
m1 = np.vstack([x, y])
print(m1)
# Horizontally stack y and z
m2 = np.hstack([y, z])
print(m2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[4 5 6 0]
 [7 8 9 0]]


# Splitting

In [59]:
# 1D array
import numpy as np
x = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
print(x)
# Indexing is as follows:
#  0  1  2  3  4  5  6  7  8
# 10 20 30 40 50 60 70 80 90
# Split x at index 3 and 6 to create 3 subarrays
x1, x2, x3 = np.split(x, [3,6])
print(x1)
print(x2)
print(x3)

[10 20 30 40 50 60 70 80 90]
[10 20 30]
[40 50 60]
[70 80 90]


In [62]:
# 2D array
import numpy as np
grid = np.arange(16).reshape(4, 4)
print(grid)
# Indexing is as follows:
#    0  1  2  3
# 0  0  1  2  3
# 1  4  5  6  7
# 2  8  9 10 11
# 3 12 13 14 15
# Split grid at row 2 to create two submatrices
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)
# Split grid at column 2 to create two submatrices
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
