In [9]:
# Using arithmetic operators on NumPy arrays
import numpy as np
x = np.arange(5)
print("x =", x)
# 1. Addition (+)
print("x + 3 =", (x+3))
# 2. Subtraction (-)
print("x - 3 =", (x-3))
# 3. Multiplication (*)
print("x * 3 =", (x*3))
# 4. Division (/)
print("x / 3 =", (x/3))
# 5. Floor division (//)
print("x // 3 =", (x//3))
# 6. Modulus (%)
print("x % 3 =", (x%3))
# 7. Exponentiation (**)
print("x ** 3 =", (x**3))
# 8. Negation (-)
print("-x =", (-x))

x = [0 1 2 3 4]
x + 3 = [3 4 5 6 7]
x - 3 = [-3 -2 -1  0  1]
x * 3 = [ 0  3  6  9 12]
x / 3 = [0.         0.33333333 0.66666667 1.         1.33333333]
x // 3 = [0 0 0 1 1]
x % 3 = [0 1 2 0 1]
x ** 3 = [ 0  1  8 27 64]
-x = [ 0 -1 -2 -3 -4]


In [18]:
# Universal functions for the above arithmetic operations
import numpy as np
x = np.arange(5)
print("x =", x)
# 1. Addition
print("x + 3 =", np.add(x, 3))
# 2. Subtraction
print("x - 3 =", np.subtract(x, 3))
# 3. Multiplication
print("x * 3 =", np.multiply(x, 3))
# 4. Division
print("x / 3 =", np.divide(x, 3))
# 5. Floor division
print("x // 3 =", np.floor_divide(x, 3))
# 6. Modulus (%)
print("x % 3 =", np.mod(x, 3))
# 7. Exponentiation
print("x ** 3 =", np.power(x, 3))
# 8. Negation
print("-x =", np.negative(x))

x = [0 1 2 3 4]
x + 3 = [3 4 5 6 7]
x - 3 = [-3 -2 -1  0  1]
x * 3 = [ 0  3  6  9 12]
x / 3 = [0.         0.33333333 0.66666667 1.         1.33333333]
x // 3 = [0 0 0 1 1]
x % 3 = [0 1 2 0 1]
x ** 3 = [ 0  1  8 27 64]
-x = [ 0 -1 -2 -3 -4]


In [23]:
# Absolute value
import numpy as np 
x = np.array([-3, -2, -1, 0, 1, 2, 3])
print(x)
# Using built-in function
print(abs(x))
# Using universal function
print(np.absolute(x))
# In case of complex numbers, it returns the magnitude
y = np.array([3-4j, 4-3j, 2+0j, 0+1j])
print(abs(y))
print(np.absolute(y))

[-3 -2 -1  0  1  2  3]
[3 2 1 0 1 2 3]
[3 2 1 0 1 2 3]
[5. 5. 2. 1.]
[5. 5. 2. 1.]


In [27]:
# Trigonometric functions
import numpy as np
# Define an array of angles
theta = np.linspace(0, np.pi, 3)
print("theta =", theta)
# 1. sine
print("sin(theta) =", np.sin(theta))
# 2. cosine
print("cos(theta) =", np.cos(theta))
# 3. tangent
print("tan(theta) =", np.tan(theta))

theta = [0.         1.57079633 3.14159265]
sin(theta) = [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [29]:
# Inverse trigonometric functions
import numpy as np
# Define an array of values
x = [-1, 0, 1]
print("x =", x)
# 1. sine inverse
print("arcsin(x) =", np.arcsin(x))
# 2. cosine inverse
print("arccos(x) =", np.arccos(x))
# 3. tangent inverse
print("arctan(x) =", np.arctan(x))

x = [-1, 0, 1]
arcsin(x) = [-1.57079633  0.          1.57079633]
arccos(x) = [3.14159265 1.57079633 0.        ]
arctan(x) = [-0.78539816  0.          0.78539816]


In [34]:
# Exponential functions
import numpy as np
x = np.array([1, 2, 3])
print("x =", x)
# 1. e^x
print("e^x =", np.exp(x))
# 2. 2^x
print("2^x =", np.exp2(x))
# 3. y^x
print("4^x =", np.power(4, x))

x = [1 2 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
4^x = [ 4 16 64]


In [36]:
# Logarithmic functions
import numpy as np
x = np.array([1, 2, 4, 10])
print("x =", x)
# 1. log(x) = Base e
print("log(x) =", np.log(x))
# 2. log2(x) = Base 2
print("log2(x) =", np.log2(x))
# 3. log10(x) = Base 10
print("log10(x) =", np.log10(x))

x = [ 1  2  4 10]
log(x) = [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [41]:
# Comparison functions
import numpy as np
a = np.array([1, 2, 3])
b = np.array([3, 2, 1])
# 1. greater than
print(np.greater(a, b))
# 2. less than
print(np.less(a, b))
# 3. greater than or equal to
print(np.greater_equal(a, b))
# 4. less than or equal to
print(np.less_equal(a, b))
# 5. equal
print(np.equal(a, b))

[False False  True]
[ True False False]
[False  True  True]
[ True  True False]
[False  True False]


In [43]:
# Logical functions
import numpy as np
a = np.array([True, False, True])
b = np.array([False, False, True])
# 1. and
print(np.logical_and(a, b))
# 2. or
print(np.logical_or(a, b))
# not
print(np.logical_not(a))

[False False  True]
[ True False  True]
[False  True False]


In [47]:
# We can specify the array where the result of the calculation will be stored using out argument
import numpy as np 
x = np.arange(5)
print(x)
# Example 1
y = np.empty(5)
print(y)
np.multiply(x, 3, out=y)
print(y)
# Example 2
z = np.zeros(10)
print(z)
np.power(2, x, out=z[::2])
print(z)

[0 1 2 3 4]
[0.0e+000 4.9e-324 9.9e-324 1.5e-323 2.0e-323]
[ 0.  3.  6.  9. 12.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]
