In [8]:
# Comparison operators
import numpy as np
x = np.array([1, 2, 3, 4, 5])
print("x =", x)
# 1. less than
print("x < 3 =", (x<3))
# 2. greater than
print("x > 3 =", (x>3))
# 3. less than or equal
print("x <= 3 =", (x<=3))
# 4. greater than or equal
print("x >= 3 =", (x>=3))
# 5. not equal
print("x != 3 =", (x!=3))
# 6. equal
print("x == 3 =", (x==3))

x = [1 2 3 4 5]
x < 3 = [ True  True False False False]
x > 3 = [False False False  True  True]
x <= 3 = [ True  True  True False False]
x >= 3 = [False False  True  True  True]
x != 3 = [ True  True False  True  True]
x == 3 = [False False  True False False]


In [11]:
# Universal functions for comparison operations
import numpy as np
x = np.array([1, 2, 3, 4, 5])
print("x =", x)
print("x < 3 =", np.less(x, 3))
print("x > 3 =", np.greater(x, 3))
print("x <= 3 =", np.less_equal(x, 3))
print("x >= 3 =", np.greater_equal(x, 3))
print("x != 3 =", np.not_equal(x, 3))
print("x == 3 =", np.equal(x, 3))

x = [1 2 3 4 5]
x < 3 = [ True  True False False False]
x > 3 = [False False False  True  True]
x <= 3 = [ True  True  True False False]
x >= 3 = [False False  True  True  True]
x != 3 = [ True  True False  True  True]
x == 3 = [False False  True False False]


In [15]:
# Comparison operations on 2D arrays
import numpy as np 
M = np.arange(12).reshape((3,4))
print(M)
print("M < 3 =")
print((M<3))
print("M > 3 =")
print(np.greater(M, 3))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
M < 3 =
[[ True  True  True False]
 [False False False False]
 [False False False False]]
M > 3 =
[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [37]:
# Counting entries
import numpy as np
# Create a 2D array filled with random integers in the range [0, 10)
M = np.random.randint(0, 10, (3,4))
print(M)
# 1. Count the no. of values less than 6
# Method 1 : count_nonzero() = Counts the no. of True entries in a Boolean array
print("M < 6 =", np.count_nonzero(M < 6))
# Method 2 : sum() = False is interpreted as 0 and True is interpreted as 1
print("M < 6 =", np.sum(M < 6))
# sum() to find result for each column
print("M < 6 (Each column) =", np.sum(M < 6, axis=0))
# sum() to find result for each row
print("M < 6 (Each row) =", np.sum(M < 6, axis=1))
# 2. any() = Evaluates whether any element is True
# Are there any values greater than 8?
print(np.any(M > 8))
# Are there any values less than zero?
print(np.any(M < 0))
# For each column
print(np.any(M == 5, axis=0))
# For each row
print(np.any(M ==3, axis=1))
# 3. all() = Evaluates wheteher all elements are True
# Are all values less than 10?
print(np.all(M < 10))
# Are all values equal to 6?
print(np.all(M == 6))
# For each column
print(np.all(M < 5, axis=0))
# For each row
print(np.all(M > 3, axis=1))

[[1 9 9 5]
 [7 6 9 1]
 [3 9 8 1]]
M < 6 = 5
M < 6 = 5
M < 6 (Each column) = [2 0 0 3]
M < 6 (Each row) = [2 1 2]
True
False
[False False False  True]
[False False  True]
True
False
[False False False False]
[False False False]


In [54]:
# SEATTLE WEATHER
import numpy as np
import pandas as pd
data = pd.read_csv('seattle_weather.csv')
data['DATE'] = pd.to_datetime(data['DATE'])
data_2015 = data[data['DATE'].dt.year == 2015]
rainfall_mm = data_2015['PRCP'].to_numpy()
print(len(rainfall_mm))
print(rainfall_mm)

365
[0.   0.06 0.   0.4  0.32 0.   0.   0.   0.01 0.23 0.06 0.   0.   0.
 0.38 0.   1.03 0.84 0.02 0.   0.   0.03 0.23 0.02 0.   0.   0.03 0.
 0.   0.   0.   0.06 0.29 0.05 0.33 1.03 0.68 0.93 0.14 0.24 0.01 0.
 0.04 0.   0.01 0.   0.   0.   0.   0.18 0.03 0.   0.   0.   0.   0.16
 0.37 0.72 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.03 0.1
 0.   0.08 0.67 2.2  0.04 0.03 0.   0.   0.16 0.15 0.04 0.32 0.3  0.2
 0.   0.04 0.   0.   0.07 0.04 0.2  0.   0.06 0.   0.   0.04 0.02 0.
 0.   0.43 0.   0.   0.55 0.13 0.   0.   0.   0.   0.   0.   0.22 0.
 0.12 0.13 0.05 0.   0.01 0.07 0.   0.   0.   0.   0.   0.   0.24 0.
 0.   0.   0.   0.   0.   0.17 0.16 0.01 0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.18 0.02 0.
 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.02 0.   0.   0.   0.   0.   0.   0.   0.   0.01 0.   0.   0.
 0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   

In [58]:
# Using boolean operators on the above data
print("Number of days without rain =", np.sum(rainfall_mm == 0))
print("Number of days with rain =", np.sum(rainfall_mm != 0))
print("Days with more than 1 =", np.sum(rainfall_mm > 1))
print("Rainy days with < 0.5 mm =", np.sum(rainfall_mm < 0.5))
print("Days with more than 1 mm and less than 2 mm =", np.sum((rainfall_mm > 1) & (rainfall_mm < 2)))

Number of days without rain = 221
Number of days with rain = 144
Days with more than 1 = 14
Rainy days with < 0.5 mm = 336
Days with more than 1 mm and less than 2 mm = 12


In [ ]:
# Boolean arrays as masks
import numpy as np
M = np.random.randint(0, 10, (3,4))
print(M)
# The following will return a boolean array
print(M < 5)
# Masking operation = Select desired values from the array meeting a specific condition
print(M[M<5])

[[4 2 0 7]
 [2 6 1 6]
 [5 5 9 1]]
[[ True  True  True False]
 [ True False  True False]
 [False False False  True]]
[4 2 0 2 1 1]


In [71]:
# Difference between keywords and/or and operators &/|
# and/or = Operate on the object as a whole
# &/| = Operate on the elements within the object

# and
print(bool(42 and 0))
# True and False = False
print(bool(42 and 24))
# True and True = True

# or
print(bool(42 or 0))
# True or False = True
print(bool(0 or 0))
# False or False = False

# &
print(bin(42))
print(bin(59))
#   1 0 1 0 1 0
# & 1 1 1 0 1 1
#   1 0 1 0 1 0
res = 42 & 59
print(bin(res))

# |
print(bin(34))
print(bin(54))
#   1 0 0 0 1 0
# | 1 1 0 1 1 0
#   1 1 0 1 1 0
res = 34 | 54
print(bin(res))

False
True
True
False
0b101010
0b111011
0b101010
0b100010
0b110110
0b110110


In [74]:
# Operators & and | are used to operate an NumPy array with boolean values
import numpy as np
A = np.array([1, 0, 1, 0, 1, 0], dtype=bool)
B = np.array([1, 1, 1, 0, 1, 1], dtype=bool)
print(A | B)

[ True  True  True False  True  True]


In [75]:
# However, keywords and/or will give error as they will try to evaluate the truth or falsehood of the entire array object
import numpy as np
A = np.array([1, 0, 1, 0, 1, 0], dtype=bool)
B = np.array([1, 1, 1, 0, 1, 1], dtype=bool)
print(A or B)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [77]:
# Operators & and | are used to evaluate boolean expressions on a given array
import numpy as np
x = np.arange(10)
print(x)
print((x>4) & (x<8))

[0 1 2 3 4 5 6 7 8 9]
[False False False False False  True  True  True False False]


In [78]:
# However, keywords and/or will give error as they will try to evaluate the truth or falsehood of the entire array object
import numpy as np
x = np.arange(10)
print(x)
print((x>4) and (x<8))

[0 1 2 3 4 5 6 7 8 9]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()